In [1]:
import numpy as np
import pandas as pd

In [26]:
input = pd.read_csv('aoc_input/aoc4.txt', header=None).squeeze()
input.columns = ['first_section', 'second_section']
input

    first_section second_section
0           71-71          42-72
1           27-28          27-99
2           15-79          14-78
3            3-36           4-36
4            5-67          32-57
5            7-85           5-86
6            2-97          97-97
7           10-73          41-55
8           34-99          34-55
9           80-80          25-80
10          50-76          50-79
11          42-70          43-70
12          95-96          81-96
13            6-7           6-94
14          37-39          17-38
15          39-95          26-96
16          52-77          53-76
17           2-99           9-95
18          23-94          79-91
19          19-78          44-77
20          47-47           1-48
21           4-88           3-52
22          51-60          50-52
23          49-90          21-89
24          76-95          97-99
25          78-96          79-95
26          90-90          77-90
27           8-73           9-72
28          54-54          54-74
29          20-40          19-40
..            ...            ...
970         60-60          60-97
971         46-66          46-67
972         18-76          19-86
973         40-67          20-67
974         13-98          14-97
975         63-65          62-64
976         22-88          21-89
977         45-77          46-78
978         14-52          14-53
979         38-59          38-60
980          1-21          21-21
981         62-70          61-62
982         50-56          23-99
983          4-96          53-97
984         68-69          19-68
985         35-76          34-76
986         29-76          30-77
987         12-91          13-90
988          7-94          96-99
989          5-85           5-81
990         56-57          57-58
991         26-26          27-98
992         12-28          11-58
993         11-32          10-32
994         10-42          10-56
995         46-63          38-62
996         31-95           3-94
997         76-82          41-75
998         87-88           4-88
999         21-33          20-32

[1000 rows x 2 columns]

In [33]:
first_input_parsed = [
    [int(row.split('-')[0]), int(row.split('-')[1])]
    for row 
    in input.first_section  
]
second_input_parsed = [
    [int(row.split('-')[0]), int(row.split('-')[1])]
    for row 
    in input.second_section  
]

In [44]:
contained = 0
for index in range(len(input)):
    if (
        (first_input_parsed[index][0] <= second_input_parsed[index][1] and first_input_parsed[index][1] >= second_input_parsed[index][1])
        or (first_input_parsed[index][0] >= second_input_parsed[index][0] and first_input_parsed[index][1] <= second_input_parsed[index][1])
    ):
        contained +=1
contained

729

In [45]:
overlap = 0
for index in range(len(input)):
    if (
        (first_input_parsed[index][1] < second_input_parsed[index][0])
        or (first_input_parsed[index][0] > second_input_parsed[index][1])
    ):
        continue
    else:
        overlap +=1
overlap

917